apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-python
  labels:
    app: mars-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mars-python
  template:
    metadata:
      labels:
        identity_template: "true"
        app: mars-python
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: mars-python-main
          securityContext:
            # privilaged is needed to create socket and bundle files
            privileged: true
        #image: us.gcr.io/scytale-registry/aws-cli:latest
          image: tsidentity/mars:latest
          command: ["sleep"]
          args: ["1000000000"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
