apiVersion: v1
kind: ServiceAccount
metadata:
  name: elon-musk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-mission
  labels:
    app: mars-mission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mars-mission
  template:
    metadata:
      labels:
        identity_template: "true"
        app: mars-mission
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: elon-musk
      containers:
        - name: mars-mission-main
          securityContext:
            # privilaged is needed to create socket and bundle files
            privileged: true
          image: us.gcr.io/scytale-registry/aws-cli:latest
          command: ["sleep"]
          args: ["1000000000"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
