apiVersion: v1
kind: ServiceAccount
metadata:
  name: elon-musk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-mission
  labels:
    app: mars-mission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mars-mission
  template:
    metadata:
      labels:
        identity_template: "true"
        app: mars-mission
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: elon-musk
      containers:
        - name: mars-mission-main
          securityContext:
            # privilaged is needed to create socket and bundle files
            privileged: true
          image: tsidentity/mars-demo:latest
          command: ["sleep"]
          args: ["1000000000"]
          env:
          - name: AG_SOCK
            value: "/run/spire/sockets/agent.sock"
          - name: S3_ROLE
            value: "arn:aws:iam::581274594392:role/mars-mission-role-01"
          - name: S3_AUD
            value: "mys3"
          - name: VAULT_ADDR
            value: "http://tsi-kube01-vault.us-south.containers.appdomain.cloud"
          - name: VAULT_ROLE
            value: "marsrole"
          - name: VAULT_SECRET
            value: "/v1/secret/data/my-super-secret"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
