apiVersion: v1
kind: ServiceAccount
metadata:
  name: elon-musk1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
  labels:
    app: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      labels:
        identity_template: "true"
        app: sidecar
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: elon-musk1
      containers:
        - name: sidecar-main
          securityContext:
            # privilaged is needed to create socket and bundle files
            privileged: true
          # image: us.gcr.io/scytale-registry/aws-cli:latest
          image: tsidentity/tornjak-example-sidecar:v0.1
          command: ["sleep"]
          args: ["1000000000"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
