apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spire-client
  labels:
    app: simple-spire-client
spec:
  selector:
    matchLabels:
      app: simple-spire-client
  template:
    metadata:
      annotations:
        spire-workload-id: eu-de/my-cluster/my-ns/my-sa/my-spire-agent-image
      labels:
        app: simple-spire-client
    spec:
      # hostPID: true
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: simple-spire-client
          image: gcr.io/spiffe-io/spire-agent:0.12.0
          command: ["sleep"]
          args: ["1000000000"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
