# .travis.yml
language: go
go:
- "1.14"

# needed for the docker pipe
services:
  - docker

env:
  - GO111MODULE=on

# avoid issues in travis with ssh / https acccess
before_script:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"

after_success:
# docker login is required if you want to push docker images.
# DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
  - test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"

cache:
  directories:
    - $GOPATH/pkg/dep

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
