apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-cli
  name: vault-cli
  namespace: trusted-identity
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "mysecret1"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-path: "mysecrets/secret-test1"
             - tsi.secret/name: "invalid"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-path: "mysecrets/secret-invalid"
             - tsi.secret/name: "non-existing"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/nothing"
               tsi.secret/local-path: "mysecrets/non-existing"
      labels:
        app: vault-cli
      name: vault-cli
    spec:
      containers:
        - name: vault-cli
          image: trustedseriviceidentity/vault-cli:v0.3
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              # provide the public access to the Vault server with TI plugin
            # value: "http://mycluster.eu-de.containers.appdomain.cloud:80"
            - name: VAULT_ROLE
              value: "demo"
