/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	cti_v1 "github.ibm.com/Brandon-Lum/ti-keyrelease/pkg/apis/cti/v1"
	versioned "github.ibm.com/Brandon-Lum/ti-keyrelease/pkg/client/clientset/versioned"
	internalinterfaces "github.ibm.com/Brandon-Lum/ti-keyrelease/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.ibm.com/Brandon-Lum/ti-keyrelease/pkg/client/listers/cti/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterTIInformer provides access to a shared informer and lister for
// ClusterTIs.
type ClusterTIInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClusterTILister
}

type clusterTIInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterTIInformer constructs a new informer for ClusterTI type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterTIInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterTIInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterTIInformer constructs a new informer for ClusterTI type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterTIInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrustedV1().ClusterTIs(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrustedV1().ClusterTIs(namespace).Watch(options)
			},
		},
		&cti_v1.ClusterTI{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterTIInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterTIInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterTIInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cti_v1.ClusterTI{}, f.defaultInformer)
}

func (f *clusterTIInformer) Lister() v1.ClusterTILister {
	return v1.NewClusterTILister(f.Informer().GetIndexer())
}
