apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "tsi-node-setup.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: ti-node-setup
  template:
    metadata:
      labels:
        name: ti-node-setup
        app: ti-node-setup
        version: v1
    spec:
      serviceAccountName: tsi-setup-admin-sa
      containers:
        - name: ti-node-setup
          image: "{{ .Values.tsiRepo }}/node-setup:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: RESETALL
              value: "{{ .Values.reset.all }}"
            - name: RESETX5C
              value: "{{ .Values.reset.x5c }}"
            - name: PRIVATEDIR
              value: "/host/tsi-secure"
            - name: CLUSTER_NAME
              value: "{{ .Values.cluster.name }}"
            - name: CLUSTER_REGION
              value: "{{ .Values.cluster.region }}"
              # get the host IP and pass as env. var
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
          - mountPath: /host/tsi-secure
            name: ti-volume
          - mountPath: /host/etc
            name: machine-id
            readOnly: true
          - mountPath: /host/logs
            name: host-logs
      volumes:
      - name: ti-volume
        hostPath:
          # directory location on host
           path: /tsi-secure
           # directory might not exist
           type: DirectoryOrCreate
      - name: machine-id
        hostPath:
          # directory location on host
           path: /etc
           type: Directory
      - name: host-logs
        hostPath:
          # directory location on host
           path: /var/log
           type: Directory
