apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsi-mutate-webhook-deployment
  labels:
    app: tsi-mutate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsi-mutate
  template:
    metadata:
      labels:
        app: tsi-mutate
    spec:
      serviceAccountName: ti-sa
      containers:
        - name: tsi-mutate
          image: trustedseriviceidentity/ti-webhook:v1.2
          imagePullPolicy: Always
          args:
            - -tsiMutateConfigFile=/etc/webhook/config/tsiMutateConfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: webhook-certs
          secret:
            secretName: tsi-mutate-webhook-certs
        - name: webhook-config
          configMap:
            name: tsi-mutate-webhook-configmap
