apiVersion: apps/v1
kind: Deployment
metadata:
  name: ti-revoker-deployment
  labels:
    app: ti-revoker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ti-revoker
    spec:
      serviceAccountName: ti-sa
      volumes:
      - name: ti-keys
        secret:
          secretName: ti-keys-config
      imagePullSecrets:
      - name: regcred
      containers:
        - name: ti-revoker
          image: trustedseriviceidentity/ti-revoker:v1.2
          imagePullPolicy: Always
          args:
            - -namespace=trusted-identity
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
          - name: ti-keys
            mountPath: /keys
            readOnly: true
