apiVersion: batch/v1
kind: Job
metadata:
  name: label-namespace
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "ti-key-release.name" . }}
    chart: {{ template "ti-key-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: label-namespace
      labels:
        app: {{ template "ti-key-release.name" . }}
        chart: {{ template "ti-key-release.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: ti-install-sa
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          command:
            - /kubectl
            - label
            - namespace
            - {{ index .Values "ti-key-release-1" "namespace" }}
            - tsi-mutate=enabled
            - --overwrite
      restartPolicy: OnFailure
