apiVersion: v1
kind: Service
metadata:
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  name: tsi-mutate-webhook-svc
  labels:
    app: tsi-mutate
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: tsi-mutate
