apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_PASSWORD
              value: testnewroot
            - name: MYSQL_ROOT_PASSWORD
              value: testroot
            - name: MYSQL_USER
              value: newroot
          image: mysql:5.7
          name: mysql57demo
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          # livenessProbe:
          #   exec:
          #     command: ["mysqladmin", "ping"]
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          readinessProbe:
            exec:
              # Check we can execute queries over TCP (skip-networking is off).
              # command: ["MYSQL_PWD=testroot mysql", "-u", "root", "-e", "SELECT 1"]
              # - bash
              # - "-c"
              # - |
              #   MYSQL_PWD=testroot mysql -uroot -e'SELECT 1'
              # ["mysql", "-u", "root", "--password=testroot",  "-e", "SELECT 1"] #
              # ["MYSQL_PWD=testroot", "mysql", "-u", "root", "-e", "SELECT 1"] #
              command:
              - bash
              - "-c"
              - |
                MYSQL_PWD=testroot mysql -uroot -s -e'SELECT 1'
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          resources: {}
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  # type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE testdb;
    USE testdb;
    DROP TABLE IF EXISTS MOVIE;
    CREATE TABLE MOVIE(  
              id int(11) NOT NULL AUTO_INCREMENT,
              name varchar(20),
              year int(11),
              director varchar(20),
              genre varchar(20),
              PRIMARY KEY (id));
    USE testdb;
    insert into MOVIE(id, name, year, director, genre) values 
    (1, "Bruce Almighty", 2003, "Tom Shaydac", "Comedy"),
    (2, "The Godfather", 1972, "Francis Ford Coppola", "Crime");