apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hyperkube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-hyperkube
    spec:
      serviceAccountName: ti-install-sa
      containers:
      - name: my-hyperkube
        image: gcr.io/google_containers/hyperkube:v1.14.3
        command: ["/bin/sleep","infinity"]
        # command: ["sh", "-c", "/tmp/ti-key-release/tsi-mutate-update.sh"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/tmp/ti-key-release"
            name: tmp-ti-key-release-configmap
      volumes:
        - name: tmp-ti-key-release-configmap
          configMap:
            name: tsi-mutate-configmap
            defaultMode: 0744
