apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myubuntu
  name: myubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myubuntu
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "mysecret1"
               tsi.secret/constraints: "region,images"
               tsi.secret/local-path: "tsi-secrets/"
             - tsi.secret/name: "mysecret2"
               tsi.secret/constraints: "region"
               tsi.secret/local-path: "tsi-secrets"
      labels:
        app: myubuntu
      name: myubuntu
    spec:
      containers:
        - name: myubuntu
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do ls /tsi-secrets; sleep 15; done;" ]
          volumeMounts:
          - mountPath: /host/etc
            name: host-etc
          - mountPath: /host/sockets
            name: tsi-sockets
          - mountPath: /host/secrets
            name: tsi-secrets
      volumes:
      - emptyDir: {}
        name: tsi-secrets
      - hostPath:
          path: /var/tsi-secure/sockets
          type: Directory
        name: tsi-sockets
      - hostPath:
          path: /etc
          type: Directory
        name: host-etc
