apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myubuntu
  name: myubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myubuntu
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "mysecret1"
               tsi.secret/constraints: "region,images"
               tsi.secret/local-path: "tsi-secrets/"
             - tsi.secret/name: "mysecret2"
               tsi.secret/constraints: "region"
               tsi.secret/local-path: "tsi-secrets"
      labels:
        app: myubuntu
      name: myubuntu
    spec:
      initContainers:
        - name: init-1
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: ['sh', '-c', "echo '**1';hostname; ls /tsi-secrets; cat /tsi-secrets/mysecret2; sleep 2; ls /tsi-secrets"]
        - name: init-2
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: ['sh', '-c', "echo '**2';hostname; ls /tsi-secrets; cat /tsi-secrets/mysecret2; sleep 2; ls /tsi-secrets"]
      containers:
        - name: myubuntu
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do ls /tsi-secrets; sleep 5; done;" ]
