apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myubuntu
  name: myubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myubuntu
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "mysecret1"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-name: "mysecrets/myubuntu-mysecret1"
             - tsi.secret/name: "mysecret2.json"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-r"
               tsi.secret/local-name: "mysecrets/myubuntu-mysecret2"
             - tsi.secret/name: "password"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-r"
               tsi.secret/local-name: "mysecrets/myubuntu-passwords"
             - tsi.secret/name: "invalid"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-name: "mysecrets/myubuntu-invalid"
             - tsi.secret/name: "non-existing"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/nothing"
               tsi.secret/local-name: "mysecrets/non-existing"
      labels:
        app: myubuntu
      name: myubuntu
    spec:
      containers:
        - name: myubuntu
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do cat /mydata; sleep 5; done;" ]
