apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myubuntunm
  name: myubuntunm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myubuntunm
  template:
    metadata:
      labels:
        app: myubuntunm
      name: myubuntunm
    spec:
      containers:
        - name: myubuntunm
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do ls /tsi-secrets; sleep 15; done;" ]
