apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  annotations:
    admission.trusted.identity/inject: "true"
    tsi.secrets: |
         - tsi.secret/name: "redis-secret1"
           tsi.secret/constraints: "region,images"
           tsi.secret/local-path: "tsi-secrets/"
         - tsi.secret/name: "redis-secret2"
           tsi.secret/constraints: "region"
           tsi.secret/local-path: "tsi-secrets"
spec:
  containers:
  - name: redis-pod
    image: redis
