apiVersion: v1
kind: Service
metadata:
  name: cl-client-service
  namespace: trusted-identity
  labels:
    app: cl-client-service
spec:
  ports:
  - port: 8000
    name: http
    targetPort: http
    protocol: TCP
  selector:
    app: cl-client
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: trusted-identity
  labels:
    app: cl-client
  name: cl-client
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
      labels:
        app: cl-client
      name: cl-client
    spec:
      containers:
        - name: cl-client
          image: trustedseriviceidentity/ti-jwt-client@sha256:a570310501a881d6cedd56ac91bca33e655df479b29d8ff8d71bf1297e7c7f8d
          imagePullPolicy: Always
          env:
            - name: TARGET_URL
              # replace the TARGET_URL value with address to Cloudant
              value: "https://59f38332-95da-4de3-a2e0-40bd768faed3-bluemix.cloudant.com"
            - name: KEYSTORE_URL
              # replace the KEYSTORE_URL value with an actual address of JWT Key Store
              value: ""
          ports:
          - name: http
            containerPort: 8000
            protocol: TCP
