/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.ibm.com/brandon-lum/ti-keyrelease/pkg/apis/cti/v1"
	scheme "github.ibm.com/brandon-lum/ti-keyrelease/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterTIsGetter has a method to return a ClusterTIInterface.
// A group's client should implement this interface.
type ClusterTIsGetter interface {
	ClusterTIs(namespace string) ClusterTIInterface
}

// ClusterTIInterface has methods to work with ClusterTI resources.
type ClusterTIInterface interface {
	Create(*v1.ClusterTI) (*v1.ClusterTI, error)
	Update(*v1.ClusterTI) (*v1.ClusterTI, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.ClusterTI, error)
	List(opts meta_v1.ListOptions) (*v1.ClusterTIList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterTI, err error)
	ClusterTIExpansion
}

// clusterTIs implements ClusterTIInterface
type clusterTIs struct {
	client rest.Interface
	ns     string
}

// newClusterTIs returns a ClusterTIs
func newClusterTIs(c *CtiV1Client, namespace string) *clusterTIs {
	return &clusterTIs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterTI, and returns the corresponding clusterTI object, and an error if there is any.
func (c *clusterTIs) Get(name string, options meta_v1.GetOptions) (result *v1.ClusterTI, err error) {
	result = &v1.ClusterTI{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustertis").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterTIs that match those selectors.
func (c *clusterTIs) List(opts meta_v1.ListOptions) (result *v1.ClusterTIList, err error) {
	result = &v1.ClusterTIList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustertis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterTIs.
func (c *clusterTIs) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustertis").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterTI and creates it.  Returns the server's representation of the clusterTI, and an error, if there is any.
func (c *clusterTIs) Create(clusterTI *v1.ClusterTI) (result *v1.ClusterTI, err error) {
	result = &v1.ClusterTI{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustertis").
		Body(clusterTI).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterTI and updates it. Returns the server's representation of the clusterTI, and an error, if there is any.
func (c *clusterTIs) Update(clusterTI *v1.ClusterTI) (result *v1.ClusterTI, err error) {
	result = &v1.ClusterTI{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustertis").
		Name(clusterTI.Name).
		Body(clusterTI).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterTI and deletes it. Returns an error if one occurs.
func (c *clusterTIs) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustertis").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterTIs) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustertis").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterTI.
func (c *clusterTIs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterTI, err error) {
	result = &v1.ClusterTI{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustertis").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
