/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	pti_v1 "github.ibm.com/Brandon-Lum/TI-KeyRelease/pkg/apis/pti/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodTIs implements PodTIInterface
type FakePodTIs struct {
	Fake *FakePtiV1
	ns   string
}

var podtisResource = schema.GroupVersionResource{Group: "pti.trusted.identity", Version: "v1", Resource: "podtis"}

var podtisKind = schema.GroupVersionKind{Group: "pti.trusted.identity", Version: "v1", Kind: "PodTI"}

// Get takes name of the podTI, and returns the corresponding podTI object, and an error if there is any.
func (c *FakePodTIs) Get(name string, options v1.GetOptions) (result *pti_v1.PodTI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podtisResource, c.ns, name), &pti_v1.PodTI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pti_v1.PodTI), err
}

// List takes label and field selectors, and returns the list of PodTIs that match those selectors.
func (c *FakePodTIs) List(opts v1.ListOptions) (result *pti_v1.PodTIList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podtisResource, podtisKind, c.ns, opts), &pti_v1.PodTIList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pti_v1.PodTIList{}
	for _, item := range obj.(*pti_v1.PodTIList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podTIs.
func (c *FakePodTIs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podtisResource, c.ns, opts))

}

// Create takes the representation of a podTI and creates it.  Returns the server's representation of the podTI, and an error, if there is any.
func (c *FakePodTIs) Create(podTI *pti_v1.PodTI) (result *pti_v1.PodTI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podtisResource, c.ns, podTI), &pti_v1.PodTI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pti_v1.PodTI), err
}

// Update takes the representation of a podTI and updates it. Returns the server's representation of the podTI, and an error, if there is any.
func (c *FakePodTIs) Update(podTI *pti_v1.PodTI) (result *pti_v1.PodTI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podtisResource, c.ns, podTI), &pti_v1.PodTI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pti_v1.PodTI), err
}

// Delete takes name of the podTI and deletes it. Returns an error if one occurs.
func (c *FakePodTIs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(podtisResource, c.ns, name), &pti_v1.PodTI{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodTIs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podtisResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &pti_v1.PodTIList{})
	return err
}

// Patch applies the patch and returns the patched podTI.
func (c *FakePodTIs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *pti_v1.PodTI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podtisResource, c.ns, name, data, subresources...), &pti_v1.PodTI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pti_v1.PodTI), err
}
