---
# Default values for spire.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# workaround since Azure doesn't support by default 10250 security port for kubelet
azure: false
# aws - enables the plugin for AWS NodeAttestor
aws: false
# openShift requires special configuration, including different security level
openShift: false

# namespace - namespace for deploying SPIRE agents and workload registrar
namespace: spire

# SPIRE specific values
# clustername needs to match between spire-config, k8s-workload-registrar config, and the actual cluster name
clustername: spire-example
# region - arbitrary label to describe the region
region: sample-region
# trustdomain is arbitrary but needs to match between spire-config and k8s-workload-registrar config
# for multi-cluster support, trustdomain must be identical for all clusters and
# SPIRE server
trustdomain: spiretest.com

# SPIRE workload registrar values:
spireAddress: spire-server
spirePort: 443
spireRegistrarImg: gcr.io/spiffe-io/k8s-workload-registrar
spireAgentImg: gcr.io/spiffe-io/spire-agent
spireVersion: 1.0.1
