---
# Default values for spire.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: networkservicemesh
tag: master
pullPolicy: IfNotPresent

# workaround since Azure doesn't support by default 10250 security port for kubelet
azure: false
namespace: spire
selfSignedCA: true

# SPIRE specific values
# clustername needs to match between spire-config, k8s-workload-registrar config, and the actual cluster name
clustername: spire-example
# trustdomain is arbitrary but needs to match between spire-config and k8s-workload-registrar config
trustdomain: spiretest.com

# SPIRE workload registrar values:
spireAddress: spire-server
spirePort: 443
spireRegistrarImg: gcr.io/spiffe-io/k8s-workload-registrar
spireAgentImg: gcr.io/spiffe-io/spire-agent
spireVersion: 0.12.1
