apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
spec:
  rules:
    # provide the actual Ingress for `host` value:
    # use the following command to get the subdomain:
    #    ibmcloud ks cluster get --cluster <cluster-name> | grep Ingress
    # any prefix can be defined as a result (e.g.):
    # - host: tsi-keycloak-v001.tsi-fra02-5240a746a818fd9d58aa25c34ecfe-0000.eu-de.containers.appdomain.cloud
    # provide the actual Ingress for `host` value:
  - host:
    http:
      paths:
      - backend:
          serviceName: tsi-keycloak
          servicePort: 9090
        path: /
