kind: Service
apiVersion: v1
metadata:
  name: tsi-keycloak
spec:
  selector:
    app: tsi-keycloak
  ports:
  - protocol: TCP
    port: 8080
    # port: 9090
    targetPort: 8080
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tsi-keycloak
  name: tsi-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsi-keycloak
  template:
    metadata:
      labels:
        app: tsi-keycloak
      name: tsi-keycloak
    spec:
      containers:
        - name: tsi-keycloak
          image: quay.io/keycloak/keycloak:19.0.3
          imagePullPolicy: Always
          args:
          - start-dev
          env:
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: adminpasswd
          - name: KC_PROXY
            value: edge
          - name: KEYCLOAK_FRONTEND_URL
            value: http://keycloak.tornjak-02-9d995c4a8c7c5f281ce13d5467ff6a94-0000.us-south.containers.appdomain.cloud/auth/
          - name: KEYCLOAK_ADMIN_URL
            value: http://keycloak.tornjak-02-9d995c4a8c7c5f281ce13d5467ff6a94-0000.us-south.containers.appdomain.cloud/auth/realms/master/admin/
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
